org: hungrypc
app: personal-website
service: personal-website

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: prod

package: 
  patterns:
    - '.next'

plugins: 
  - serverless-esbuild
  - serverless-finch

functions:
  render:
    handler: handlers/index.handler
    events:
      - http: 'GET /'
      - http: 'GET /{proxy+}'

resources:
  Resources:
    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}/bucket
    FrontendDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Origins:
            - Id: render
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
              DomainName:
               {
                 'Fn::Join':
                   [
                     '',
                     [
                       { 'Ref': 'ApiGatewayRestApi' },
                       '.execute-api.${self:provider.region}.amazonaws.com',
                     ],
                   ],
               }
              OriginPath: '/${self:provider.stage}'
            - Id: bucket
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
              DomainName:
               {
                 'Fn::Select':
                   [
                     1,
                     {
                       'Fn::Split':
                         ['http://', { 'Fn::GetAtt': ['FrontendBucket', 'WebsiteURL'] }],
                     },
                   ],
               }
          DefaultCacheBehavior:
            AllowedMethods: ['GET', 'HEAD', 'OPTIONS']
            CachedMethods: ['HEAD', 'GET']
            Compress: true
            DefaultTTL: 3600
            TargetOriginId: render
            ViewerProtocolPolicy: redirect-to-https
            PathPattern: /_next/static/*
          CacheBehaviors:
            - AllowedMethods: ['GET', 'HEAD', 'OPTIONS']
              CachedMethods: ['HEAD', 'GET']
              Compress: true
              TargetOriginId: bucket
              ForwardedValues:
              QueryString: false
              ViewerProtocolPolicy: redirect-to-https
              PathPattern: /_next/static/*

custom:
  esbuild:
    bundle: true
    minify: true
    exclude: '*'
  outputFileTracing:
    additionalFiles:
      - ./pages/index.tsx
  client:
    bucketName: ${self.service}
    distributionFolder: dist
